stages:
  - deploy

deploy:

  image: debian:latest
  stage: deploy
  environment:
    name: devel
    url: https://powerdrive.skni.umcs.pl

  before_script:
    - "command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )"

    - eval $(ssh-agent -s)

    - ssh-add <(echo "$SSH_PRIVATE_KEY")

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "echo 'TEST CONENCTION'"

  script:
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/gitlab-deploy/powerdrive/baggins && docker compose -f docker-compose.prod.yml down"
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/gitlab-deploy/powerdrive/baggins && git pull"
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "cd /home/gitlab-deploy/powerdrive/baggins && docker compose -f docker-compose.prod.yml up --build --force-recreate --no-deps -d "

  after_script:
    - rm -rf ~/.ssh

  only:
    - master
    - feature/ci-cd
