export enum ErrorCodeEnum {
  UNKNOWN = "UNKNOWN",
  REGISTER_ATTEMPT_FAILED = "REGISTER_ATTEMPT_FAILED",
  LOGIN_ATTEMPT_FAILED = "LOGIN_ATTEMPT_FAILED",
  PASSWORD_UPPERCASE_ERROR = "PASSWORD_UPPERCASE_ERROR",
  PASSWORD_LOWERCASE_ERROR = "PASSWORD_LOWERCASE_ERROR",
  PASSWORD_DIGIT_ERROR = "PASSWORD_DIGIT_ERROR",
  PASSWORD_SPECIAL_CHARACTER_ERROR = "PASSWORD_SPECIAL_CHARACTER_ERROR",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  USERNAME_ALREADY_IN_USE = "USERNAME_ALREADY_IN_USE",
}
