export enum LoopTypeEnum {
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  MONTHLY = "MONTHLY",
  MONTHLY_FIRST = "MONTHLY_FIRST",
  MONTHLY_SECOND = "MONTHLY_SECOND",
  MONTHLY_THIRD = "MONTHLY_THIRD",
  MONTHLY_FOURTH = "MONTHLY_FOURTH",
  MONTHLY_LAST = "MONTHLY_LAST",
  YEARLY = "YEARLY",
}
