export enum PathEnum {
  LOGIN = "login",
  REGISTER = "register",
  ACCOUNT_RETRIEVAL = "retrieve",
  RETRIEVE_LINK_SENT = "link-sent",
  PASSWORD_RESET = "password-reset",
  APP = "app",
  DRIVE = "drive",
  CALENDAR = "calendar",
  NOTES = "notes",
  HOME = "home",
  SHARED = "shared",
  FILES = "files",
  FAVORITES = "favorites",
  DELETED = "deleted",
  SETTINGS = "settings",
  GENERAL = "general",
  ACCOUNT = "account",
}
