export enum SuccessCodeEnum {
  LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
  REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL",
  LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL",
  FILE_UPLOAD_SUCCESSFUL = "FILE_UPLOAD_SUCCESSFUL",
  FILES_UPLOAD_SUCCESSFUL = "FILES_UPLOAD_SUCCESSFUL",
  FILE_DOWNLOAD_SUCCESSFUL = "FILE_DOWNLOAD_SUCCESSFUL",
  FILES_DOWNLOAD_SUCCESSFUL = "FILES_DOWNLOAD_SUCCESSFUL",
  FILE_DELETE_SUCCESSFUL = "FILE_DELETE_SUCCESSFUL",
  FILES_DELETE_SUCCESSFUL = "FILES_DELETE_SUCCESSFUL",
}
